components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateCompany:
      type: object
      required:
        - companyName
        - organizationId
      properties:
        companyName:
          type: string
          description: Name of the company
        organizationId:
          type: integer
          description: ID of the organization to associate

    GeoPoint:
      type: object
      description: Geographical location in GeoJSON Point format
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
          enum: [Point]
          description: Must be "Point" for GeoJSON
        coordinates:
          type: array
          description: [longitude, latitude]
          items:
            type: number
          minItems: 2
          maxItems: 2

    CreateField:
      type: object
      required:
        - fieldName
        - companyId
      properties:
        fieldName:
          type: string
          description: Name of the field
        companyId:
          type: integer
          description: ID of the company to associate the field with
        location:
          $ref: '#/components/schemas/GeoPoint'

    CreateSector:
      type: object
      required:
        - sectorName
        - fieldId
        - culture
      properties:
        sectorName:
          type: string
          description: Name of the sector
        fieldId:
          type: integer
          description: ID of the field to associate the sector with
        culture:
          type: string
          description: Main culture of the sector
        cultureType:
          type: string
          description: Optional type of the culture
        location:
          $ref: '#/components/schemas/GeoPoint'
        prescriptive:
          type: boolean
          description: Optional prescriptive flag
        advice:
          type: boolean
          description: Optional advice flag
        dripperCapacity:
          type: number
          format: double
          description: Optional dripper capacity 
          example: 1.5
        sprinklerCapacity:
          type: number
          format: double
          description: Optional sprinkler capacity 
        dripperScalingFactor:
          type: number
          format: double
          description: Optional dripper scaling factor

    CreateThesis:
      type: object
      required:
        - thesisName
        - sectorId
      properties:
        thesisName:
          type: string
          description: Name of the thesis
        sectorId:
          type: integer
          description: ID of the sector to assign the thesis to
        validFrom: 
          type: number
          description: Optional timestamp of thesis validity start (Seconds elapsed since 01/01/1970 - 00:00 )

    CreateSignal:
      type: object
      required:
        - typeId
        - x
        - y
        - z
      properties:
        typeId:
          type: integer
          description: Signal type ID
        description:
          type: string
          description: Optional signal description
        x:
          type: number
          description: Signal x coordinate
        y:
          type: number
          description: Signal y coordinate
        z:
          type: number
          description: Signal z coordinate
        virtual:
          type: boolean
          descriptio: True if it's virtual
        unit:
          type: string
          description: Measurement unit of the signal 

    CreateDevice:
      type: object
      required:
        - type
        - providerId
        - location
        - signals
      properties:
        type:
          type: string
          description: Type of the device
        providerId:
          type: integer
          description: ID of the provider
        description:
          type: string
          description: Optional description of the device
        location:
          $ref: '#/components/schemas/GeoPoint'
        signals:
          type: array
          description: Array of signals associated with the device
          items:
            $ref: '#/components/schemas/CreateSignal'
    
    SignalTargetType:
      type: string
      enum:
        - field
        - sector
        - thesis

    SignalAssignment:
      type: object
      required:
        - deviceId
        - targetId
        - targetType
      properties:
        deviceId:
          type: integer
          description: Device id of the signals getting assigned
        targetId:
          type: integer
          description: Id of the signal target 
        targetType:
          $ref: '#/components/schemas/SignalTargetType'
          description: Type of the target entity
        validFrom: 
          type: number
          description: Optional timestamp of association validity start (Seconds elapsed since 01/01/1970 - 00:00 )
