components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateCompany:
      type: object
      required:
        - companyName
        - organizationId
      properties:
        companyName:
          type: string
          description: Name of the company
        organizationId:
          type: integer
          description: ID of the organization to associate
    